FROM python:3.11-slim

WORKDIR /src

COPY ./requirements.txt ./app.py ./

RUN apt-get update && apt-get install git -y && apt-get install curl -y

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "app.py"]
